import { Poppins } from "next/font/google";
import "./globals.css";
import { MemeProvider } from "./context/memeContext";
import Navabar from "./components/Navbar";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Select font weights
  variable: "--font-poppins", // Custom CSS variable
});

export const metadata = {
  title: "Memez",
  description: "Generated by create next app",
  icons: "/meme.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ToastContainer position="top-center" autoClose={2000} />
        <Navabar />
        <MemeProvider>{children}</MemeProvider>
      </body>
    </html>
  );
}
